#!/usr/bin/env bash
# ==============================================================================
# generate-changelog.sh - สร้าง CHANGELOG.md จาก git commit messages
#
# Usage:
#   ./scripts/generate-changelog.sh                  # สร้างจาก 50 commits ล่าสุด
#   ./scripts/generate-changelog.sh --max 100        # 100 commits
#   ./scripts/generate-changelog.sh --output file.md # กำหนด output file
# ==============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

OUTPUT_FILE="CHANGELOG.md"
MAX_COMMITS=50

log_info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }

# Parse args
while [[ $# -gt 0 ]]; do
    case "$1" in
        --max)    MAX_COMMITS="$2"; shift 2 ;;
        --output) OUTPUT_FILE="$2"; shift 2 ;;
        *)        shift ;;
    esac
done

current_version=$(grep -E '^version\s*=' Cargo.toml | head -1 | sed -E 's/^version\s*=\s*"([^"]+)"/\1/' 2>/dev/null || echo "unknown")

log_info "Generating changelog from last $MAX_COMMITS commits..."

# สร้าง temp files สำหรับแต่ละ type
TMP_DIR=$(mktemp -d)
trap "rm -rf $TMP_DIR" EXIT

FEAT_FILE="$TMP_DIR/feat.md"
FIX_FILE="$TMP_DIR/fix.md"
DOCS_FILE="$TMP_DIR/docs.md"
REFACTOR_FILE="$TMP_DIR/refactor.md"
PERF_FILE="$TMP_DIR/perf.md"
TEST_FILE="$TMP_DIR/test.md"
CHORE_FILE="$TMP_DIR/chore.md"
OTHER_FILE="$TMP_DIR/other.md"

touch "$FEAT_FILE" "$FIX_FILE" "$DOCS_FILE" "$REFACTOR_FILE" "$PERF_FILE" "$TEST_FILE" "$CHORE_FILE" "$OTHER_FILE"

count=0
while IFS='|' read -r short_hash subject author date; do
    [[ -z "$short_hash" ]] && continue
    ((count++)) || true

    # Parse commit type
    entry="- ${subject} (\`${short_hash}\`) - ${date}"

    if [[ "$subject" =~ ^feat ]]; then
        echo "$entry" >> "$FEAT_FILE"
    elif [[ "$subject" =~ ^fix ]]; then
        echo "$entry" >> "$FIX_FILE"
    elif [[ "$subject" =~ ^docs ]]; then
        echo "$entry" >> "$DOCS_FILE"
    elif [[ "$subject" =~ ^refactor ]]; then
        echo "$entry" >> "$REFACTOR_FILE"
    elif [[ "$subject" =~ ^perf ]]; then
        echo "$entry" >> "$PERF_FILE"
    elif [[ "$subject" =~ ^test ]]; then
        echo "$entry" >> "$TEST_FILE"
    elif [[ "$subject" =~ ^chore ]]; then
        echo "$entry" >> "$CHORE_FILE"
    else
        echo "$entry" >> "$OTHER_FILE"
    fi
done < <(git log --format="%h|%s|%an|%ad" --date=short -n "$MAX_COMMITS")

log_ok "Processed $count commits"

# เขียน output
{
    echo "# Changelog"
    echo ""
    echo "All notable changes to this project will be documented in this file."
    echo ""
    echo "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),"
    echo "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)."
    echo ""
    echo "---"
    echo ""
    echo "## [Unreleased] - $(date -u +'%Y-%m-%d')"
    echo ""
    echo "> Version: $current_version | Total commits: $count"
    echo ""

    # Features
    if [[ -s "$FEAT_FILE" ]]; then
        echo "### ✨ Features"
        echo ""
        cat "$FEAT_FILE"
        echo ""
    fi

    # Bug Fixes
    if [[ -s "$FIX_FILE" ]]; then
        echo "### 🐛 Bug Fixes"
        echo ""
        cat "$FIX_FILE"
        echo ""
    fi

    # Documentation
    if [[ -s "$DOCS_FILE" ]]; then
        echo "### 📚 Documentation"
        echo ""
        cat "$DOCS_FILE"
        echo ""
    fi

    # Refactoring
    if [[ -s "$REFACTOR_FILE" ]]; then
        echo "### ♻️ Code Refactoring"
        echo ""
        cat "$REFACTOR_FILE"
        echo ""
    fi

    # Performance
    if [[ -s "$PERF_FILE" ]]; then
        echo "### ⚡ Performance"
        echo ""
        cat "$PERF_FILE"
        echo ""
    fi

    # Tests
    if [[ -s "$TEST_FILE" ]]; then
        echo "### 🧪 Tests"
        echo ""
        cat "$TEST_FILE"
        echo ""
    fi

    # Maintenance
    if [[ -s "$CHORE_FILE" ]]; then
        echo "### 🔧 Maintenance"
        echo ""
        cat "$CHORE_FILE"
        echo ""
    fi

    # Other
    if [[ -s "$OTHER_FILE" ]]; then
        echo "### 📝 Other Changes"
        echo ""
        cat "$OTHER_FILE"
        echo ""
    fi

    echo "---"
    echo ""
    echo "*Generated by generate-changelog.sh on $(date -u +'%Y-%m-%d %H:%M:%S UTC')*"
} > "$OUTPUT_FILE"

log_ok "Changelog saved to: $OUTPUT_FILE"
